name: "OCI Terraform"

on:
  push:
    branches: ["main"]
  pull_request:

env:
  TF_VAR_tenancy_ocid: ${{ secrets.TENANCY_OCID }}
  TF_VAR_compartment_ocid: ${{ secrets.COMPARTMENT_OCID }}
  TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
  TF_VAR_region: ${{ secrets.REGION }}

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: self-hosted
    environment: ocitest #Environemnt name

    # Use the Bash shell
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.12

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
